-- =============================================================
-- 00_export_data.sql — Run this in your CURRENT account BEFORE it expires
-- Exports all table data to a named stage as Parquet files
-- Then download them with: GET @HACKATHON.RETAIL.EXPORT_STAGE file:///path/to/local/data/
-- =============================================================

USE DATABASE HACKATHON;
USE SCHEMA RETAIL;
USE WAREHOUSE HACKATHON_WH;

CREATE OR REPLACE STAGE EXPORT_STAGE;

-- Core tables (Parquet)
COPY INTO @EXPORT_STAGE/abt/ FROM ABT FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/buy/ FROM BUY FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/abt_buy_perfect_mapping/ FROM ABT_BUY_PERFECT_MAPPING FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/product_matches_final/ FROM PRODUCT_MATCHES_FINAL FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/pricing_history/ FROM PRICING_HISTORY FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/matches_vector/ FROM MATCHES_VECTOR FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/matches_fuzzy/ FROM MATCHES_FUZZY FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;
COPY INTO @EXPORT_STAGE/matches_llm_verified/ FROM MATCHES_LLM_VERIFIED FILE_FORMAT=(TYPE=PARQUET) HEADER=TRUE OVERWRITE=TRUE;

-- NOTE: ABT_EMBEDDINGS and BUY_EMBEDDINGS have VECTOR columns that
-- cannot be exported as Parquet. You will regenerate them in the new
-- account using 06_regenerate_embeddings.sql.
