-- =============================================================
-- 01_setup.sql — Create warehouses, database, schema, and tables
-- =============================================================

CREATE WAREHOUSE IF NOT EXISTS HACKATHON_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS HACKATHON;
CREATE SCHEMA IF NOT EXISTS HACKATHON.RETAIL;

USE DATABASE HACKATHON;
USE SCHEMA RETAIL;
USE WAREHOUSE HACKATHON_WH;

-- Source data tables
CREATE OR REPLACE TABLE ABT (
    ID NUMBER(38,0),
    NAME VARCHAR(2000),
    DESCRIPTION VARCHAR(10000),
    PRICE FLOAT
);

CREATE OR REPLACE TABLE BUY (
    ID NUMBER(38,0),
    NAME VARCHAR(2000),
    DESCRIPTION VARCHAR(10000),
    MANUFACTURER VARCHAR(500),
    PRICE FLOAT
);

CREATE OR REPLACE TABLE ABT_BUY_PERFECT_MAPPING (
    ABT_ID NUMBER(38,0),
    BUY_ID NUMBER(38,0)
);

-- Embedding tables
CREATE OR REPLACE TABLE ABT_EMBEDDINGS (
    ID NUMBER(38,0),
    NAME VARCHAR(2000),
    DESCRIPTION VARCHAR(10000),
    PRICE FLOAT,
    EMBEDDING VECTOR(FLOAT, 1024)
);

CREATE OR REPLACE TABLE BUY_EMBEDDINGS (
    ID NUMBER(38,0),
    NAME VARCHAR(2000),
    DESCRIPTION VARCHAR(10000),
    MANUFACTURER VARCHAR(500),
    PRICE FLOAT,
    EMBEDDING VECTOR(FLOAT, 1024)
);

-- Intermediate match tables
CREATE OR REPLACE TABLE MATCHES_VECTOR (
    ABT_ID NUMBER(38,0),
    ABT_NAME VARCHAR(2000),
    BUY_ID NUMBER(38,0),
    BUY_NAME VARCHAR(2000),
    COSINE_SIMILARITY FLOAT
);

CREATE OR REPLACE TABLE MATCHES_FUZZY (
    ABT_ID NUMBER(38,0),
    ABT_NAME VARCHAR(2000),
    BUY_ID NUMBER(38,0),
    BUY_NAME VARCHAR(2000),
    FUZZY_SCORE NUMBER(10,6)
);

CREATE OR REPLACE TABLE MATCHES_LLM_VERIFIED (
    ABT_ID NUMBER(38,0),
    ABT_NAME VARCHAR(2000),
    BUY_ID NUMBER(38,0),
    BUY_NAME VARCHAR(2000),
    COSINE_SIMILARITY FLOAT,
    LLM_RESPONSE VARCHAR(16777216)
);

-- Final results
CREATE OR REPLACE TABLE PRODUCT_MATCHES_FINAL (
    ABT_ID NUMBER(38,0),
    ABT_NAME VARCHAR(2000),
    ABT_DESCRIPTION VARCHAR(10000),
    ABT_PRICE FLOAT,
    BUY_ID NUMBER(38,0),
    BUY_NAME VARCHAR(2000),
    BUY_DESCRIPTION VARCHAR(10000),
    BUY_PRICE FLOAT,
    MANUFACTURER VARCHAR(500),
    VECTOR_SCORE FLOAT,
    FUZZY_SCORE NUMBER(10,6),
    LLM_CONFIDENCE FLOAT,
    LLM_MATCH BOOLEAN,
    LLM_REASON VARCHAR(16777216),
    COMBINED_CONFIDENCE FLOAT,
    MATCH_TIER VARCHAR(6),
    PRICE_DIFFERENCE FLOAT,
    PRICE_GAP_PCT FLOAT
);

CREATE OR REPLACE TABLE PRICING_HISTORY (
    PRODUCT_ID NUMBER(38,0),
    RETAILER VARCHAR(3),
    PRICE_DATE DATE,
    PRICE FLOAT
);
