-- =============================================================
-- 06_load_data.sql — Upload & load data into the new account
-- =============================================================
-- Before running this:
--   1. Create stage:  CREATE STAGE HACKATHON.RETAIL.IMPORT_STAGE;
--   2. Upload files:  PUT file:///path/to/data/abt/* @HACKATHON.RETAIL.IMPORT_STAGE/abt/;
--                     PUT file:///path/to/data/buy/* @HACKATHON.RETAIL.IMPORT_STAGE/buy/;
--                     ... repeat for all folders
-- =============================================================

USE DATABASE HACKATHON;
USE SCHEMA RETAIL;
USE WAREHOUSE HACKATHON_WH;

CREATE OR REPLACE STAGE IMPORT_STAGE;

-- After uploading files via PUT, run:
COPY INTO ABT FROM @IMPORT_STAGE/abt/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO BUY FROM @IMPORT_STAGE/buy/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO ABT_BUY_PERFECT_MAPPING FROM @IMPORT_STAGE/abt_buy_perfect_mapping/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO PRODUCT_MATCHES_FINAL FROM @IMPORT_STAGE/product_matches_final/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO PRICING_HISTORY FROM @IMPORT_STAGE/pricing_history/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO MATCHES_VECTOR FROM @IMPORT_STAGE/matches_vector/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO MATCHES_FUZZY FROM @IMPORT_STAGE/matches_fuzzy/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
COPY INTO MATCHES_LLM_VERIFIED FROM @IMPORT_STAGE/matches_llm_verified/ FILE_FORMAT=(TYPE=PARQUET) MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE;
